### ISSUE TITLE
ofl_structs_match_put_masked need to be changed

### ISSUE THREAD

**Issue by simhond** [CPqD/nox13oflib#1]
Please pay attention that this function needs to be changed accordingly:

void ofl_structs_match_put_masked(struct ofl_match *match, uint32_t header, T value, T mask){
    struct ofl_match_tlv *m = (struct ofl_match_tlv *) malloc(sizeof (struct ofl_match_tlv));
    int len = ((header) & 0xff);

```
m->header = header & 0xffffff00; /* This line is missing !!! */

/*set the masked bit */
m->header |= 1 << 8;

/* multiply the header len by 2 */

m->header |= ((header & 0xff) << 1); /* bug bug bug -> should be & instead of && */

m->value = (uint8_t*) malloc(len*2);
memcpy(m->value, &value, len);
memcpy(m->value + len, &mask, len);
hmap_insert(&match->match_fields,&m->hmap_node, hash_int(header, 0));
match->header.length += len * 2 + 4;
```

}

**Comment by ederlf** [comment]
Hi Simon, thanks for the report.

Do you want to submit a pull request or should I apply it directly?

**Comment by simhond** [comment]
Hi,

Thanks. No, please apply it yourself directly.

Simhon.

**Comment by ederlf** [comment]
Fixed! 
Thanks!
